#include <iostream.h>
#include<stdio.h>
#include<conio.h>
int main ()
{long double i,s,n;
clrscr();
cout<<"     *      *      *      *      *";
cout<<"\n";
cout<<"     *      *      *      *      *";
cout<<"\n";
for(i=5;i>=1;i--)
{
for(s=1;s<5;s++)
cout<<" ";
for(s=1;s<4;s++)
cout<<"*";
for(s=1;s<5;s++)
cout<<" ";
for(s=1;s<4;s++)
cout<<"*";
for(s=1;s<5;s++)
cout<<" ";
for(s=1;s<4;s++)
cout<<"*";
for(s=1;s<5;s++)
cout<<" ";
for(s=1;s<4;s++)
cout<<"*";
for(s=1;s<5;s++)
cout<<" ";
for(s=1;s<4;s++)
cout<<"*";
cout<<"\n";
}
for(i=5;i>=1;i--)
{
for(s=1;s<45;s++)
cout<<"*";
cout<<"\n";

cout<<"\n";
}
cout<<"27/01/2002-27/01/2019 \n";
cout<<"HAPPY BIRTHDAY BRO \n";
cout<<"enter his age and find out how long he will live";
cin>>n;
for(n;n>=0;n++)
cout<<"still alive :-"<<n<<"\n";
getchar ();
return 0;
}
			//HAPPY BIRTHDAY BRO
			// SWEET 17
